spring.application.name=reviews-service

spring.datasource.url=jdbc:mysql://localhost:3306/quickorder_reviews
spring.datasource.username=root
spring.datasource.password=CompletoItaliano123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8088