spring.application.name=order-items-service

spring.datasource.url=jdbc:mysql://localhost:3306/quickorder_order_items
spring.datasource.username=root
spring.datasource.password=CompletoItaliano123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8084